-- VERIFICA IL NOME DEL DATABASE E MODIFICALO SE NECESSARIO
-- VERIFICA SE LA CODIFICA DEI CARATTERI E' SUPPORTATA DAL TUO SERVER MYSQL

CREATE DATABASE IF NOT EXISTS votazione_romani
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_general_ci;
USE votazione_romani;

CREATE TABLE indirizzo (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(40) NOT NULL
);

CREATE TABLE studenti (
  email VARCHAR(320) NOT NULL PRIMARY KEY,
  nome VARCHAR(40) NOT NULL,
  cognome VARCHAR(40) NOT NULL,
  classe INT NOT NULL,
  sezione CHAR(1) NOT NULL,
  fk_indirizzo INT NOT NULL,
  FOREIGN KEY (fk_indirizzo) REFERENCES indirizzo(id)
);

CREATE TABLE admin (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(30) NOT NULL UNIQUE,
  password CHAR(60) NOT NULL
);

CREATE TABLE sondaggi (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  titolo VARCHAR(50) NOT NULL,
  descrizione VARCHAR(300),
  data DATE,
  turni INT NOT NULL,
  durata_turno INT NOT NULL,
  min_voti INT NOT NULL,
  max_voti INT NOT NULL
);

CREATE TABLE opzioni (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  titolo VARCHAR(50) NOT NULL,
  descrizione VARCHAR(300),
  durata INT NOT NULL DEFAULT 1,
  posti INT NOT NULL DEFAULT 30,
  fk_sondaggio INT NOT NULL,
  FOREIGN KEY (fk_sondaggio) REFERENCES sondaggi(id)
);

CREATE TABLE scelte (
  fk_studente VARCHAR(320) NOT NULL,
  fk_opzione INT NOT NULL,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (fk_studente, fk_opzione),
  FOREIGN KEY (fk_studente) REFERENCES studenti(email),
  FOREIGN KEY (fk_opzione) REFERENCES opzioni(id)
);
